# Generated by Django 2.1 on 2018-08-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180809_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_username',
            new_name='name',
        ),
    ]
